(progn
    (format t "~%Ouverture du système expert")

    ;; Initialisation des variables globale à NIL
    (setq *CADEAUX-SE* NIL)

    ;; Fonction d'ajout d'un cadeau
    (defun add-gift (conditions gift description)
        (let ((id (gentemp "A")))
            (set id (list (list 'conditions conditions) (list 'gift gift)(list 'description description)))
            (pushnew id *CADEAUX-SE*)
        )
    )

    (format t"~%Génération d'idée de cadeau")
    (add-gift '((petitBudget)(bebe)(utilitaire)) "Berceaux, Tétine ou Habits" "")
    (add-gift '((petitBudget)(bebe)(mignon)) "Peluche ou jouet" "")
    (add-gift '((petitBudget)(enfant)(utilitaire)(sport))"Habits ou matériel lié au sport" "")
    (add-gift '((petitBudget)(enfant)(utilitaire)(art))"Matériel de dessin ou de peinture" "")
    (add-gift '((petitBudget)(enfant)(utilitaire)(musique))"Ecouteur" "")
    (add-gift '((petitBudget)(enfant)(utilitaire)(lecture))"Marque Page" "")
    (add-gift '((petitBudget)(enfant)(utilitaire)(technologie))"Kano" "")
    (add-gift '((petitBudget)(enfant)(utilitaire)(autre))"Habits" "")
    (add-gift '((petitBudget)(enfant)(sentimental))"Album photo" "")
    (add-gift '((petitBudget)(enfant)(experience)(sport))"Place pour un match de son équipe favorite" "")
    (add-gift '((petitBudget)(enfant)(experience)(msuique))"Place de concert" "")
    (add-gift '((petitBudget)(enfant)(experience)(jeux))"Session d'escape Game" "")
    (add-gift '((petitBudget)(enfant)(experience)(art))"Entrée pour un musé ou une exposition" "")
    (add-gift '((petitBudget)(enfant)(experience)(dessinAnime))"Place de cinéma (dessin animé)" "")
    (add-gift '((petitBudget)(enfant)(divertissement)(jeux)(video))"Une clef d'activation pour un jeux" "")
    (add-gift '((petitBudget)(enfant)(divertissement)(jeux)(societe))"Monopoly" "")
    (add-gift '((petitBudget)(enfant)(divertissement)(jeux)(carte))"Uno" "")
    (add-gift '((petitBudget)(enfant)(divertissement)(technologie))"Lego Technique" "")
    (add-gift '((petitBudget)(enfant)(divertissement)(bricolage))"Lego" "")
    (add-gift '((petitBudget)(enfant)(divertissement)(dessinAnime))"DVD de dessin animé" "")
    (add-gift '((petitBudget)(enfant)(divertissement)(lecture))"Livre" "")
    (add-gift '((petitBudget)(enfant)(divertissement)(musique))"CD de son artiste préféré" "")
    (add-gift '((petitBudget)(adolescent)(utilitaire)(sport))"Habits ou matériel lié au sport" "")
    (add-gift '((petitBudget)(adolescent)(utilitaire)(technologie))"Périphérique, carte éléctronique programmable" "")
    (add-gift '((petitBudget)(adolescent)(utilitaire)(art))"Matériel de dessin ou de peinture" "")
    (add-gift '((petitBudget)(adolescent)(utilitaire)(musique))"Ecouteur" "")
    (add-gift '((petitBudget)(adolescent)(utilitaire)(lecture))"Marque page" "")
    (add-gift '((petitBudget)(adolescent)(utilitaire)(autre))"Habit" "")
    (add-gift '((petitBudget)(adolescent)(experience)(technologie))"Entrée dans un musée technologique" "")
    (add-gift '((petitBudget)(adolescent)(experience)(sport))"Place pour un match de son équipe favorite" "")
    (add-gift '((petitBudget)(adolescent)(experience)(musique))"Place pour un concert" "")
    (add-gift '((petitBudget)(adolescent)(experience)(art))"Place pour une pièce de théâtre ou une exposition" "")
    (add-gift '((petitBudget)(adolescent)(experience)(lecture))"Dédicace" "")
    (add-gift '((petitBudget)(adolescent)(experience)(cinema))"Place pour aller voir un film" "")
    (add-gift '((petitBudget)(adolescent)(experience)(jeux))"Escape Game" "")
    (add-gift '((petitBudget)(adolescent)(sentimental)(proche))"Album photo ou Fleur" "")
    (add-gift '((petitBudget)(adolescent)(sentimental)(amoureux))"Des roses ou un bracelet" "")
    (add-gift '((petitBudget)(adolescent)(divertissement)(musique))"CD de son artiste" "")
    (add-gift '((petitBudget)(adolescent)(divertissement)(lecture))"Livre ou BD" "")
    (add-gift '((petitBudget)(adolescent)(divertissement)(jeux)(video))"Une clef d'activation pour un jeux vidéo" "")
    (add-gift '((petitBudget)(adolescent)(divertissement)(jeux)(societe))"Splendor" "")
    (add-gift '((petitBudget)(adolescent)(divertissement)(jeux)(carte))"Skyjo" "")
    (add-gift '((petitBudget)(adulte)(utilitaire)(cuisine))"Air Fryer ou tout autre ustensile de cuisine" "")
    (add-gift '((petitBudget)(adulte)(utilitaire)(technologie))"Support téléphone ou tablette" "")
    (add-gift '((petitBudget)(adulte)(utilitaire)(bricolage))"Caisse à outil miniature" "")
    (add-gift '((petitBudget)(adulte)(experience)(cinema))"Place(s) pour un film en plein air" "")
    (add-gift '((petitBudget)(adulte)(experience)(art))"Place(s) pour un vernissage" "")
    (add-gift '((petitBudget)(adulte)(experience)(sport))"Carte cadeau pour un cour de yoga" "")
    (add-gift '((petitBudget)(adulte)(experience)(cuisine))"Place pour un cours de cuisine" "")
    (add-gift '((petitBudget)(adulte)(experience)(lecture))"Place pour 'la grande librairie', ou une dédicace" "")
    (add-gift '((petitBudget)(adulte)(sentimental)(amoureux))"Cadre d'un souvenir commun" "")
    (add-gift '((petitBudget)(adulte)(sentimental)(proche))"Carte personnalisé avec un mot" "")
    (add-gift '((petitBudget)(adulte)(divertissement)(alcool))"Bière de dégustation" "")
    (add-gift '((petitBudget)(adulte)(divertissement)(jeux)(societe))"Casse-tête" "")
    (add-gift '((petitBudget)(adulte)(divertissement)(dessinAnime))"Coffret DVD d'un dessin animé culte" "")
    (add-gift '((petitBudget)(personneAgee)(utilitaire)(cuisine))"Tablier personnalisé par toute la famille" "")
    (add-gift '((petitBudget)(personneAgee)(utilitaire)(lecture))"Loupe pour lire ou une liseuse" "")
    (add-gift '((petitBudget)(personneAgee)(utilitaire)(voyage))"Guide de voyage" "")
    (add-gift '((petitBudget)(personneAgee)(experience)(art))"Place pour un atelier de peinture" "")
    (add-gift '((petitBudget)(personneAgee)(experience)(cinema))"Carte d'abonnement pour des sorties cinema" "")
    (add-gift '((petitBudget)(personneAgee)(experience)(musique))"Place pour un concert d'un orchestre" "")
    (add-gift '((petitBudget)(personneAgee)(experience)(sport))"Bon pour une séance de yoga" "")
    (add-gift '((petitBudget)(personneAgee)(sentimental)(proche))"Famileo (marque déposée) ou un album photo familial" "")
    (add-gift '((petitBudget)(personneAgee)(sentimental)(amoureux))"cadre numérique pour afficher plusieurs souvenir" "")
    (add-gift '((petitBudget)(personneAgee)(divertissement)(alcool))"Vin en fonction des goûts" "")
    (add-gift '((petitBudget)(personneAgee)(divertissement)(art))"Kit de peinture" "")
)